### ISSUE TITLE
restoration sites historic - amalgamate info - tracking sources

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/restoration_wedzin_kwa_2024#45]
draft in process product stored in `collaborative_qgis/sites_restoration.gpkg`

Will point to it after initial commit.

- [x] Wet'suwet'en First Nation sites - Gaboury and Smith proposed 
- [ ] Wet'suwet'en First Nation sites - Gaboury and Smith completed 
- [x] #48
- [ ] adding Site Level Details of MWMT Stakeholder Tracking Table_RevisedApr27.xlsx to applicable sites
- [ ] can just use PSCIS for fish passage remediation sites.  Peacock needs to go to PSCIS first if not completed by Canfor

**Comment by lucy-schick** [comment]
accidentally closed wrong issue in commit, should be #48. Make sure to reopen this issue when PR gets merged.

**Comment by NewGraphEnvironment** [comment]
reopening

need to add Price 2014 and Nadina 1998 prescriptions to tracking file too
